version: 2
jobs:
  build:
    working_directory: ~/my-project/frontend
    docker:
      - image: circleci/node:12.20-browsers
    steps:
      - checkout:
         path: ~/my-project
      #- restore_cache:
      #    key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
